export const FORMULARIO_PROYECTO = 'PROYECTO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const PROYECTO_ERROR = 'PROYECTO_ERROR';
export const CLEAR_ACTIVE_PROJECT = 'CLEAR_ACTIVE_PROJECT';



export const OBTENER_TAREAS_PROYECTO = 'OBTENER_TAREAS-PROYECTO';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_TAREA = 'VALIDAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const EDIT_TAREA = 'EDIT_TAREA';
export const CLEAR_TAREA = 'CLEAR_TAREA';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_CORRECTO = 'REGISTRO_CORRECTO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const LOGIN_CORRECTO = 'LOGIN_CORRECTO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';




